name: .NET SpecFlow Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Debug Repository Structure
      run: |
        echo "Current Directory: $(pwd)"
        ls -R
      working-directory: ${{ github.workspace }}

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore
      working-directory: SwagProject  # ✅ FIXED PATH

    - name: Build project
      run: dotnet build --no-restore --configuration Release
      working-directory: SwagProject  # ✅ FIXED PATH

    - name: List available tests (for debugging)
      run: dotnet test --list-tests
      working-directory: SwagProject  # ✅ FIXED PATH

    - name: Run SpecFlow Tests
      run: dotnet test --no-build --configuration Release --filter "FullyQualifiedName~ExecutionOfSaucedemo"
      working-directory: SwagProject  # ✅ FIXED PATH
