name: .NET CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Debug Repository Structure
        run: |
          echo "Current Directory: $(pwd)"
          ls -R
        working-directory: ${{ github.workspace }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x  # Change version if needed

      - name: Restore Dependencies
        run: dotnet restore
        working-directory: ${{ github.workspace }}

      - name: Build Project
        run: dotnet build --configuration Release --no-restore
        working-directory: ${{ github.workspace }}

      - name: Run Tests
        run: dotnet test --configuration Release --no-build --logger trx
        working-directory: ${{ github.workspace }}
